### PR TITLE
fix: download error

### LINKED ISSUE #7: Can't install some versions in macOS
**Describe the bug**

Currently, we can't install some versions of Pandoc(e.g. 3.1.2) in macOS.

**Steps to reproduce**

1. `asdf install pandoc@3.1.2`
2. Download failure

**Expected behavior**

Download correctly

**Screenshots**

**Additional context**

Maybe, we can't install many other versions in macOS.

### PR DESCRIPTION
**Pull request by sys9kdr**
ref #7

### CODE REVIEW

**Comment by sys9kdr** [comment]
@Fbrisset Most of the issues at #7 have been resolved. I think it should work now, please check it out.

**Comment by Fbrisset** [comment]
I think I will manage unique versions and not display non-installable versions

**Comment by Fbrisset** [comment]
@sys9kdr Please note release 2.0 has a unique name for the file.

**Review by Fbrisset — APPROVED** [review]

**Comment by Fbrisset** [comment]
I merge the branch. And I apply the fix for non-installable versions is file 2.0

**Comment by sys9kdr** [comment]
@Fbrisset 

> I think I want to manage unique versions and not show non-installable versions.

Do you mean that when listing versions, skip versions that do not have a zipped/gzipped executable? e.g. 1.12, 2.0 or other versions.

Ok, but we should discuss this in another issues.　I think we should merge this PR first.

**Comment by Fbrisset** [comment]
> @Fbrisset
> 
> > I think I want to manage unique versions and not show non-installable versions.
> 
> Do you mean that when listing versions, skip versions that do not have a zipped/gzipped executable? e.g. 1.12, 2.0 or other versions.
> 
> Ok, but we should discuss this in another issues.　I think we should merge this PR first.

yes I think it is better not to display versions which do not have an executable. (I specified it in the readme).
Later we can do cleaner management of exceptions and also can be compiled pandoc before version 2.0.

**Pull request merged**
